### ISSUE TITLE
Could not find module

### ISSUE THREAD

**Issue by ghost** [onechiporenko/ember-paper-modals-manager#1]
Hi, I got following error:

Uncaught Error: Could not find module `ember-paper-modals-manager/services/paper-modals-manager` imported from `panel/services/modals-manager`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at Class._extractDefaultExport (index.js:408)
    at Class.resolveOther (index.js:110)
    at Class.superWrapper [as resolveOther] (ember-utils.js:403)
    at Class.resolve (resolver.js:133)
    at _resolve (container.js:952)

ember-cli: 3.1.4
ember: 3.22 - pod structure
node: 8.11.2

Thanks.

**Comment by onechiporenko** [comment]
Hi, @SKMan. Import in your app should be 
```javascript
import ModalsManager from 'ember-paper-modals-manager/services/modals-manager';
```

**Comment by ghost** [comment]
My mistake. Works now. Thank you.

**Comment by mpugach** [comment]
@onechiporenko I had the same issue on the second step of this guide https://onechiporenko.github.io/ember-paper-modals-manager/docs/install

I needed to create `services/modals-manager` in order it to work somehow
```js
export { default } from 'ember-paper-modals-manager/services/modals-manager';
```

Now my template is
```handlebars
{{#paper-button
  onClick=(action 'confirmAndDestroy')
}}
  Remove
{{/paper-button}}
```

the controller
```js
  modalsManager: service(),

  actions: {
    confirmAndDestroy() {
      this.modalsManager
        .confirm({title: 'Confirm Title', body: 'Confirm Body'})
        .then(() => {
          console.log('confirmed'); //DEBUG
        })
        .catch(() => {
          console.log('not confirmed'); //DEBUG
        });
    }
  },
```

So I press the button, the modal appears and I see the error in console

```
translate3d-mixin.js:109 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': The provided selector is empty.
    at Class.calculateZoomToOrigin (http://localhost:4200/assets/vendor.js:122078:62)
    at Class.<anonymous> (http://localhost:4200/assets/vendor.js:121982:39)
    at ComputedProperty.get (http://localhost:4200/assets/vendor.js:45868:36)
    at _get (http://localhost:4200/assets/vendor.js:44690:35)
    at Class.get (http://localhost:4200/assets/vendor.js:54217:34)
    at Class.<anonymous> (http://localhost:4200/assets/vendor.js:121991:43)
    at ComputedProperty.get (http://localhost:4200/assets/vendor.js:45868:36)
    at _get (http://localhost:4200/assets/vendor.js:44690:35)
    at RootPropertyReference.compute (http://localhost:4200/assets/vendor.js:35263:40)
    at RootPropertyReference.value (http://localhost:4200/assets/vendor.js:35140:53)
```

After I press Yes or No, the action is executed correctly but the modal stays opened and another error in the console

```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': The provided selector is empty.
    at Class.calculateZoomToOrigin (http://localhost:4200/assets/vendor.js:122078:62)
```

from this point the modal stops responding on my actions

Ember 3.3.1
Ember Paper 1.0.0-beta.21
Modals Manager 1.3.0

**Comment by onechiporenko** [comment]
@mpugach, there are two issues here. One is already fixed (you can try to use v1.3.1 ember-paper-modals-manager). Second is about `querySelector`. You can try to use `ember-paper@1.0.0-beta.18` or lower.

**Comment by onechiporenko** [comment]
@mpugach please try a latest `ember-paper-modals-dialog@1.3.2`.

**Comment by mpugach** [comment]
thank you @onechiporenko
